# Generated by Django 4.2.10 on 2025-04-25 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("html_content", models.TextField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("page_links", models.JSONField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "run_frequency",
                    models.PositiveIntegerField(
                        default=0, help_text="Frequency in hours (0 for one-time)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraping_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrapedDataElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("heading", "Heading"),
                            ("paragraph", "Paragraph"),
                            ("link", "Link"),
                            ("image", "Image"),
                            ("list", "List"),
                            ("table", "Table"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "scraped_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="scraper_app.scrapeddata",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="scrapeddata",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraped_data",
                to="scraper_app.scrapingtask",
            ),
        ),
    ]
